[tool.poetry]
name = "src"
version = "0.1.0"
description = "tools to help coding bots on codingame"
authors = ["Matt Matt <matthieu.chambery@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.13,<3.14"
pandas = "^3.0.3"
numpy = "^2.4.4"
scipy = "^1.17.1"
pyyaml = "^6.0.3"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
